/**
 * Battle4Arena backend project configuration.
 *
 * Keep safe, non-secret defaults here so `.env` only needs secrets and
 * deployment-specific overrides. Values in `.env` always win.
 */

export const PROJECT_CONFIG = {
  server: {
    port: 3000,
    nodeEnv: "development",
    role: "realtime",
    platform: "local",
    enableRealtime: true,
    enableBackgroundWorkers: true,
  },
  urls: {
    corsOrigins: [
      "http://localhost:8080",
      "https://battle4arena.fun",
      "https://battle4arena.vercel.app",
    ],
    appPublicUrl: "https://battle4arena.fun",
    localApiPublicUrl: "http://localhost:3000",
    fastApiPublicUrl: "https://api.battle4arena.fun/api/v1",
    realtimeApiPublicUrl: "https://realtime.battle4arena.fun/api/v1",
    deepLinkScheme: "battle4arena",
  },
  database: {
    clusterName: "battle4arena",
    maxPoolSize: 50,
    minPoolSize: 0,
    maxIdleTimeMs: 60_000,
    waitQueueTimeoutMs: 5_000,
  },
  auth: {
    accessTokenExpiry: "10d",
    refreshTokenExpiry: "20d",
    userCacheTtlMs: 10_000,
    userCacheMax: 1_000,
  },
  oauth: {
    facebookGraphVersion: "v25.0",
    allowedReturnOrigins: ["https://battle4arena.fun", "http://localhost:8080"],
    allowedReturnSchemes: ["battle4arena"],
    loginCodeTtlMs: 300_000,
  },
  email: {
    from: "Battle4Arena <hello@battle4arena.fun>",
    providerOrder: "hostinger,sendplus",
    delegateToFastApi: true,
    fastApiUrl: "https://api.battle4arena.fun/api/v1",
    enableDispatch: true,
    allowLocalSend: false,
    forceQueue: false,
    delegateTimeoutMs: 15_000,
    sendInline: true,
    fireAndForget: false,
    queueEnabled: false,
    workerEnabled: false,
    logToDb: false,
    maxRetries: 4,
    retryDelayMs: 1_500,
    healthTtlMs: 30_000,
    logProviderResult: false,
    queuePrefix: "b4a",
    removeOnComplete: 50,
    removeOnFail: 2_000,
    workerConcurrency: 4,
    smtp: {
      host: "smtp.hostinger.com",
      port: 465,
      secure: true,
      pool: true,
    },
    hostinger: {
      host: "smtp.hostinger.com",
      port: 465,
      secure: true,
      pool: true,
    },
    sendplus: {
      host: "smtp-pulse.com",
      port: 465,
      secure: true,
      pool: true,
    },
  },
  passwordReset: {
    otpExpiryMinutes: 5,
    resendCooldownMinutes: 5,
    linkExpiryDays: 4,
    resendWindowMinutes: 60,
    maxResends: 5,
    maxVerifyAttempts: 5,
    grantExpiryMinutes: 15,
  },
  rateLimits: {
    globalWindowMs: 900_000,
    globalMax: 600,
    authWindowMs: 900_000,
    authMax: 25,
    passwordResetWindowMs: 900_000,
    passwordResetMax: 5,
    walletWindowMs: 600_000,
    walletMax: 30,
    chatWindowMs: 60_000,
    chatMax: 90,
    reportWindowMs: 600_000,
    reportMax: 8,
    moderationWindowMs: 600_000,
    moderationMax: 60,
    internalEmailWindowMs: 60_000,
    internalEmailMax: 120,
  },
  realtime: {
    socketRateLimitWindowMs: 60_000,
    socketRateLimitMax: 60,
    adminMonitoringPushMs: 10_000,
  },
  performance: {
    slowApiLogMs: 1_500,
    logSlowApi: true,
    notificationDeliveryConcurrency: 10,
    reportDuplicateWindowMs: 43_200_000,
  },
  uploads: {
    uploadDir: "uploads",
    chatUploadMaxBytes: 5 * 1024 * 1024,
    chatUploadMaxSize: "5mb",
    chatStorageProvider: "telestore",
    chatStorageLocalFallback: false,
    profileAvatarUploadLimit: "2mb",
    profileBannerUploadLimit: "4mb",
    profileAvatarMaxBytes: 2 * 1024 * 1024,
    profileBannerMaxBytes: 4 * 1024 * 1024,
  },
  teleStore: {
    apiBaseUrl: "https://storageapi.battle4arena.fun/api/v1",
    publicBaseUrl: "https://storageapi.battle4arena.fun",
    chatRootFolderName: "Battle4Arena Live Chat",
    profileRootFolderName: "Battle4Arena Profiles",
    visibility: "public",
    timeoutMs: 20_000,
  },
  walletFees: {
    depositPercent: 2,
    withdrawPercent: 2,
    transferPercent: 0,
    walletTransferPercent: 0,
    organizerEarningPercent: 0,
    refundPercent: 0,
    tournamentEntryPercent: 2,
    winningPercent: 0,
    bonusPercent: 0,
  },
  notifications: {
    vapidSubject: "mailto:hello@battle4arena.fun",
  },
  admin: {
    highValueDebitAlert: 5_000,
  },
};

export const ENV_DEFAULTS = {
  PORT: PROJECT_CONFIG.server.port,
  NODE_ENV: PROJECT_CONFIG.server.nodeEnv,
  SERVER_ROLE: PROJECT_CONFIG.server.role,
  SERVER_PLATFORM: PROJECT_CONFIG.server.platform,
  ENABLE_REALTIME: PROJECT_CONFIG.server.enableRealtime,
  ENABLE_BACKGROUND_WORKERS: PROJECT_CONFIG.server.enableBackgroundWorkers,

  CORS_ORIGIN: PROJECT_CONFIG.urls.corsOrigins.join(","),
  APP_PUBLIC_URL: PROJECT_CONFIG.urls.appPublicUrl,
  API_PUBLIC_URL: PROJECT_CONFIG.urls.localApiPublicUrl,
  FAST_API_PUBLIC_URL: PROJECT_CONFIG.urls.fastApiPublicUrl,
  REALTIME_API_PUBLIC_URL: PROJECT_CONFIG.urls.realtimeApiPublicUrl,
  APP_DEEPLINK_SCHEME: PROJECT_CONFIG.urls.deepLinkScheme,

  DB_CLUSTER_NAME: PROJECT_CONFIG.database.clusterName,
  MONGODB_MAX_POOL_SIZE: PROJECT_CONFIG.database.maxPoolSize,
  MONGODB_MIN_POOL_SIZE: PROJECT_CONFIG.database.minPoolSize,
  MONGODB_MAX_IDLE_TIME_MS: PROJECT_CONFIG.database.maxIdleTimeMs,
  MONGODB_WAIT_QUEUE_TIMEOUT_MS: PROJECT_CONFIG.database.waitQueueTimeoutMs,

  ACCESS_TOKEN_EXPIRY: PROJECT_CONFIG.auth.accessTokenExpiry,
  REFRESH_TOKEN_EXPIRY: PROJECT_CONFIG.auth.refreshTokenExpiry,
  AUTH_USER_CACHE_TTL_MS: PROJECT_CONFIG.auth.userCacheTtlMs,
  AUTH_USER_CACHE_MAX: PROJECT_CONFIG.auth.userCacheMax,

  FACEBOOK_GRAPH_VERSION: PROJECT_CONFIG.oauth.facebookGraphVersion,
  OAUTH_ALLOWED_RETURN_ORIGINS: PROJECT_CONFIG.oauth.allowedReturnOrigins.join(","),
  OAUTH_ALLOWED_RETURN_SCHEMES: PROJECT_CONFIG.oauth.allowedReturnSchemes.join(","),
  OAUTH_LOGIN_CODE_TTL_MS: PROJECT_CONFIG.oauth.loginCodeTtlMs,

  EMAIL_FROM: PROJECT_CONFIG.email.from,
  EMAIL_PROVIDER_ORDER: PROJECT_CONFIG.email.providerOrder,
  EMAIL_DELEGATE_TO_FAST_API: PROJECT_CONFIG.email.delegateToFastApi,
  EMAIL_FAST_API_URL: PROJECT_CONFIG.email.fastApiUrl,
  ENABLE_EMAIL_DISPATCH: PROJECT_CONFIG.email.enableDispatch,
  EMAIL_ALLOW_LOCAL_SEND: PROJECT_CONFIG.email.allowLocalSend,
  EMAIL_FORCE_QUEUE: PROJECT_CONFIG.email.forceQueue,
  EMAIL_DELEGATE_TIMEOUT_MS: PROJECT_CONFIG.email.delegateTimeoutMs,
  EMAIL_SEND_INLINE: PROJECT_CONFIG.email.sendInline,
  EMAIL_FIRE_AND_FORGET: PROJECT_CONFIG.email.fireAndForget,
  EMAIL_QUEUE_ENABLED: PROJECT_CONFIG.email.queueEnabled,
  EMAIL_WORKER_ENABLED: PROJECT_CONFIG.email.workerEnabled,
  EMAIL_LOG_TO_DB: PROJECT_CONFIG.email.logToDb,
  EMAIL_MAX_RETRIES: PROJECT_CONFIG.email.maxRetries,
  EMAIL_RETRY_DELAY_MS: PROJECT_CONFIG.email.retryDelayMs,
  EMAIL_HEALTH_TTL_MS: PROJECT_CONFIG.email.healthTtlMs,
  EMAIL_LOG_PROVIDER_RESULT: PROJECT_CONFIG.email.logProviderResult,
  EMAIL_QUEUE_PREFIX: PROJECT_CONFIG.email.queuePrefix,
  EMAIL_REMOVE_ON_COMPLETE: PROJECT_CONFIG.email.removeOnComplete,
  EMAIL_REMOVE_ON_FAIL: PROJECT_CONFIG.email.removeOnFail,
  EMAIL_WORKER_CONCURRENCY: PROJECT_CONFIG.email.workerConcurrency,

  SMTP_HOST: PROJECT_CONFIG.email.smtp.host,
  SMTP_PORT: PROJECT_CONFIG.email.smtp.port,
  SMTP_SECURE: PROJECT_CONFIG.email.smtp.secure,
  SMTP_POOL: PROJECT_CONFIG.email.smtp.pool,
  HOSTINGER_SMTP_HOST: PROJECT_CONFIG.email.hostinger.host,
  HOSTINGER_SMTP_PORT: PROJECT_CONFIG.email.hostinger.port,
  HOSTINGER_SMTP_SECURE: PROJECT_CONFIG.email.hostinger.secure,
  HOSTINGER_SMTP_POOL: PROJECT_CONFIG.email.hostinger.pool,
  SENDPLUS_SMTP_HOST: PROJECT_CONFIG.email.sendplus.host,
  SENDPLUS_SMTP_PORT: PROJECT_CONFIG.email.sendplus.port,
  SENDPLUS_SMTP_SECURE: PROJECT_CONFIG.email.sendplus.secure,
  SENDPLUS_SMTP_POOL: PROJECT_CONFIG.email.sendplus.pool,

  PASSWORD_RESET_OTP_EXPIRY_MINUTES: PROJECT_CONFIG.passwordReset.otpExpiryMinutes,
  PASSWORD_RESET_RESEND_COOLDOWN_MINUTES: PROJECT_CONFIG.passwordReset.resendCooldownMinutes,
  PASSWORD_RESET_LINK_EXPIRY_DAYS: PROJECT_CONFIG.passwordReset.linkExpiryDays,
  PASSWORD_RESET_RESEND_WINDOW_MINUTES: PROJECT_CONFIG.passwordReset.resendWindowMinutes,
  PASSWORD_RESET_MAX_RESENDS: PROJECT_CONFIG.passwordReset.maxResends,
  PASSWORD_RESET_MAX_VERIFY_ATTEMPTS: PROJECT_CONFIG.passwordReset.maxVerifyAttempts,
  PASSWORD_RESET_GRANT_EXPIRY_MINUTES: PROJECT_CONFIG.passwordReset.grantExpiryMinutes,

  RATE_LIMIT_GLOBAL_WINDOW_MS: PROJECT_CONFIG.rateLimits.globalWindowMs,
  RATE_LIMIT_GLOBAL_MAX: PROJECT_CONFIG.rateLimits.globalMax,
  RATE_LIMIT_AUTH_WINDOW_MS: PROJECT_CONFIG.rateLimits.authWindowMs,
  RATE_LIMIT_AUTH_MAX: PROJECT_CONFIG.rateLimits.authMax,
  RATE_LIMIT_PASSWORD_RESET_WINDOW_MS: PROJECT_CONFIG.rateLimits.passwordResetWindowMs,
  RATE_LIMIT_PASSWORD_RESET_MAX: PROJECT_CONFIG.rateLimits.passwordResetMax,
  RATE_LIMIT_WALLET_WINDOW_MS: PROJECT_CONFIG.rateLimits.walletWindowMs,
  RATE_LIMIT_WALLET_MAX: PROJECT_CONFIG.rateLimits.walletMax,
  RATE_LIMIT_CHAT_WINDOW_MS: PROJECT_CONFIG.rateLimits.chatWindowMs,
  RATE_LIMIT_CHAT_MAX: PROJECT_CONFIG.rateLimits.chatMax,
  RATE_LIMIT_REPORT_WINDOW_MS: PROJECT_CONFIG.rateLimits.reportWindowMs,
  RATE_LIMIT_REPORT_MAX: PROJECT_CONFIG.rateLimits.reportMax,
  RATE_LIMIT_MODERATION_WINDOW_MS: PROJECT_CONFIG.rateLimits.moderationWindowMs,
  RATE_LIMIT_MODERATION_MAX: PROJECT_CONFIG.rateLimits.moderationMax,
  INTERNAL_EMAIL_RATE_LIMIT_WINDOW_MS: PROJECT_CONFIG.rateLimits.internalEmailWindowMs,
  INTERNAL_EMAIL_RATE_LIMIT_MAX: PROJECT_CONFIG.rateLimits.internalEmailMax,

  SOCKET_RATE_LIMIT_WINDOW_MS: PROJECT_CONFIG.realtime.socketRateLimitWindowMs,
  SOCKET_RATE_LIMIT_MAX: PROJECT_CONFIG.realtime.socketRateLimitMax,
  ADMIN_MONITORING_PUSH_MS: PROJECT_CONFIG.realtime.adminMonitoringPushMs,

  SLOW_API_LOG_MS: PROJECT_CONFIG.performance.slowApiLogMs,
  LOG_SLOW_API: PROJECT_CONFIG.performance.logSlowApi,
  NOTIFICATION_DELIVERY_CONCURRENCY: PROJECT_CONFIG.performance.notificationDeliveryConcurrency,
  REPORT_DUPLICATE_WINDOW_MS: PROJECT_CONFIG.performance.reportDuplicateWindowMs,

  UPLOAD_DIR: PROJECT_CONFIG.uploads.uploadDir,
  CHAT_UPLOAD_MAX_BYTES: PROJECT_CONFIG.uploads.chatUploadMaxBytes,
  CHAT_UPLOAD_MAX_SIZE: PROJECT_CONFIG.uploads.chatUploadMaxSize,
  CHAT_STORAGE_PROVIDER: PROJECT_CONFIG.uploads.chatStorageProvider,
  CHAT_STORAGE_LOCAL_FALLBACK: PROJECT_CONFIG.uploads.chatStorageLocalFallback,
  PROFILE_AVATAR_UPLOAD_LIMIT: PROJECT_CONFIG.uploads.profileAvatarUploadLimit,
  PROFILE_BANNER_UPLOAD_LIMIT: PROJECT_CONFIG.uploads.profileBannerUploadLimit,
  PROFILE_AVATAR_MAX_BYTES: PROJECT_CONFIG.uploads.profileAvatarMaxBytes,
  PROFILE_BANNER_MAX_BYTES: PROJECT_CONFIG.uploads.profileBannerMaxBytes,

  TELESTORE_API_BASE_URL: PROJECT_CONFIG.teleStore.apiBaseUrl,
  TELESTORE_PUBLIC_BASE_URL: PROJECT_CONFIG.teleStore.publicBaseUrl,
  TELESTORE_CHAT_ROOT_FOLDER_NAME: PROJECT_CONFIG.teleStore.chatRootFolderName,
  TELESTORE_PROFILE_ROOT_FOLDER_NAME: PROJECT_CONFIG.teleStore.profileRootFolderName,
  TELESTORE_CHAT_VISIBILITY: PROJECT_CONFIG.teleStore.visibility,
  TELESTORE_TIMEOUT_MS: PROJECT_CONFIG.teleStore.timeoutMs,

  PLATFORM_FEE_DEPOSIT_PERCENT: PROJECT_CONFIG.walletFees.depositPercent,
  PLATFORM_FEE_WITHDRAW_PERCENT: PROJECT_CONFIG.walletFees.withdrawPercent,
  PLATFORM_FEE_TRANSFER_PERCENT: PROJECT_CONFIG.walletFees.transferPercent,
  PLATFORM_FEE_WALLET_TRANSFER_PERCENT: PROJECT_CONFIG.walletFees.walletTransferPercent,
  PLATFORM_FEE_ORGANIZER_EARNING_PERCENT: PROJECT_CONFIG.walletFees.organizerEarningPercent,
  PLATFORM_FEE_REFUND_PERCENT: PROJECT_CONFIG.walletFees.refundPercent,
  PLATFORM_FEE_TOURNAMENT_ENTRY_PERCENT: PROJECT_CONFIG.walletFees.tournamentEntryPercent,
  PLATFORM_FEE_WINNING_PERCENT: PROJECT_CONFIG.walletFees.winningPercent,
  PLATFORM_FEE_BONUS_PERCENT: PROJECT_CONFIG.walletFees.bonusPercent,

  VAPID_SUBJECT: PROJECT_CONFIG.notifications.vapidSubject,
  ADMIN_HIGH_VALUE_DEBIT_ALERT: PROJECT_CONFIG.admin.highValueDebitAlert,
};

export const applyProjectConfigDefaults = () => {
  for (const [key, value] of Object.entries(ENV_DEFAULTS)) {
    if (process.env[key] === undefined || process.env[key] === "") {
      process.env[key] = String(value);
    }
  }
};

export default PROJECT_CONFIG;
