import dotenv from 'dotenv'
dotenv.config()

const PORT = process.env.PORT
const CORS_ORIGIN = process.env.CORS_ORIGIN
const MONGODB_URI = process.env.MONGODB_URI
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET
const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET
const REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN_EXPIRY
const RAPIDAPI_KEY = process.env.RAPIDAPI_KEY
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
const FACEBOOK_APP_ID = process.env.FACEBOOK_APP_ID
const FACEBOOK_APP_SECRET = process.env.FACEBOOK_APP_SECRET
const FACEBOOK_GRAPH_VERSION = process.env.FACEBOOK_GRAPH_VERSION || "v25.0"
const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID
const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET
const MONGODB_MAX_POOL_SIZE = process.env.MONGODB_MAX_POOL_SIZE
const MONGODB_MIN_POOL_SIZE = process.env.MONGODB_MIN_POOL_SIZE
const MONGODB_MAX_IDLE_TIME_MS = process.env.MONGODB_MAX_IDLE_TIME_MS
const MONGODB_WAIT_QUEUE_TIMEOUT_MS = process.env.MONGODB_WAIT_QUEUE_TIMEOUT_MS

export {
    PORT,
    CORS_ORIGIN,
    MONGODB_URI,
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRY,
    RAPIDAPI_KEY,
    GOOGLE_CLIENT_ID,
    FACEBOOK_APP_ID,
    FACEBOOK_APP_SECRET,
    FACEBOOK_GRAPH_VERSION,
    RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET,
    MONGODB_MAX_POOL_SIZE,
    MONGODB_MIN_POOL_SIZE,
    MONGODB_MAX_IDLE_TIME_MS,
    MONGODB_WAIT_QUEUE_TIMEOUT_MS
}
